import SwiftUI
import AppKit
import TokenMukbangKit

/// "Yesterday's plate" — the retrospective detail pane (ADR-0020, docs/VISION.md).
/// Shows the metadata layer (A) immediately and offers on-demand content insights (B)
/// generated by the local `claude` CLI. Reflection mirror, 먹방 voice.
struct RetrospectiveView: View {
    @ObservedObject var model: AppModel
    @Environment(\.colorScheme) private var scheme
    @Environment(\.themeMood) private var mood
    @State private var copied = false

    var body: some View {
        VStack(alignment: .leading, spacing: DS.section) {
            if let retro = model.retrospective, retro.totalConsumed > 0 {
                pageHeader(retro)        // page-level title + Copy (scopes Copy to the whole retro)
                header(retro)
                metadataCard(retro)      // A — always available, token-free
                topicsCard(retro)        // B — on-demand, spends tokens
            } else {
                emptyState
            }
        }
    }

    /// Page-level header — title on the left, "Copy whole retrospective" on the right.
    /// Lives outside the cards so the Copy action reads as page-scoped, not card-scoped.
    private func pageHeader(_ retro: RetrospectiveSummary) -> some View {
        HStack(alignment: .firstTextBaseline) {
            Text("Retrospective").font(.title3.weight(.semibold))
            Spacer()
            copyButton(retro)
        }
    }

    // MARK: Header — the plate + baseline delta

    private func header(_ retro: RetrospectiveSummary) -> some View {
        GlassTile(scheme: scheme) {
            VStack(alignment: .leading, spacing: DS.intra) {
                Text("YESTERDAY'S PLATE").dsEyebrow()
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    Text(RetrospectiveSummary.tokens(retro.totalConsumed)).font(.system(size: 28, weight: .bold))
                    Text("eaten").font(.callout).foregroundStyle(.secondary)
                    Spacer()
                    if let delta = retro.baselineDeltaPercent { baselineChip(delta) }
                }
                Text(RetrospectiveSummary.dateLabel(retro.periodStart, timeZone: model.settings.resolvedTimeZone))
                    .font(DS.captionFont).foregroundStyle(.tertiary)
            }
            .padding(DS.section)
        }
    }

    /// Copies the full retrospective (A + B if generated) to the clipboard as plain text.
    private func copyButton(_ retro: RetrospectiveSummary) -> some View {
        Button {
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.setString(retro.plainTextReport(timeZone: model.settings.resolvedTimeZone), forType: .string)
            copied = true
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { copied = false }
        } label: {
            Label(copied ? "Copied" : "Copy",
                  systemImage: copied ? "checkmark" : "doc.on.doc")
                .font(.caption)
        }
        .buttonStyle(.borderless)
        .foregroundStyle(copied ? AnyShapeStyle(.green) : AnyShapeStyle(.secondary))
    }

    private func baselineChip(_ delta: Double) -> some View {
        let up = delta >= 0
        let txt = String(format: "%@%.0f%% vs usual", up ? "↑" : "↓", abs(delta))
        return Text(txt)
            .font(.caption.weight(.semibold))
            .padding(.horizontal, 8).padding(.vertical, 3)
            .background(mood.accent.opacity(0.18), in: Capsule())
            .foregroundStyle(.primary)
    }

    // MARK: A — metadata (what / how)

    private func metadataCard(_ retro: RetrospectiveSummary) -> some View {
        GlassTile(scheme: scheme) {
            VStack(alignment: .leading, spacing: DS.section) {
                if !retro.projects.isEmpty {
                    section("MENU (by project)") {
                        ForEach(retro.projects.prefix(5)) { p in
                            row(p.project, RetrospectiveSummary.tokens(p.tokens),
                                fraction: frac(p.tokens, retro.totalConsumed))
                        }
                    }
                }
                if !retro.casts.isEmpty {
                    section("CAST (by model)") {
                        ForEach(retro.casts.prefix(5)) { c in
                            row(c.castName, RetrospectiveSummary.tokens(c.tokens),
                                fraction: frac(c.tokens, retro.totalConsumed))
                        }
                    }
                }
                if let label = RetrospectiveSummary.busiestHourLabel(retro.hourly, timeZone: model.settings.resolvedTimeZone) {
                    section("WHEN") {
                        Text("Busiest around \(label)")
                            .font(.callout).foregroundStyle(.secondary)
                    }
                }
            }
            .padding(DS.section)
        }
    }

    // MARK: B — content topics (on demand)

    private func topicsCard(_ retro: RetrospectiveSummary) -> some View {
        GlassTile(scheme: scheme) {
            VStack(alignment: .leading, spacing: DS.intra) {
                Text("HOW YOU'RE EATING").dsEyebrow()
                if let topics = retro.topics {
                    tldrBadge(topics.summary)
                    ForEach(topics.themes, id: \.self) { tip in
                        Label(tip, systemImage: "lightbulb.fill")
                            .font(.caption).labelStyle(.titleAndIcon)
                            .foregroundStyle(.secondary)
                            .textSelection(.enabled)
                    }
                    HStack(spacing: 10) {
                        Text(sourceNote(topics)).font(.caption2).foregroundStyle(.tertiary)
                        Spacer()
                        regenerateButton          // re-run is always available (overwrites the cache)
                    }
                    .padding(.top, 2)
                } else if !model.claudeAvailable {
                    degradeNote
                } else {
                    generatePrompt
                }
            }
            .padding(DS.section)
        }
    }

    /// The coach's headline takeaway, elevated as a TL;DR callout above the detailed tips.
    private func tldrBadge(_ text: String) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: "sparkles").font(.caption).foregroundStyle(mood.accent)
            VStack(alignment: .leading, spacing: 2) {
                Text("TL;DR").font(.caption2.weight(.bold)).foregroundStyle(mood.accent)
                Text(text).font(.callout.weight(.medium))
                    .fixedSize(horizontal: false, vertical: true)
                    .textSelection(.enabled)
            }
        }
        .padding(10)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(mood.accent.opacity(scheme == .light ? 0.12 : 0.16),
                    in: RoundedRectangle(cornerRadius: 8, style: .continuous))
    }

    /// Re-run the on-demand summarizer; overwrites the cached topics. Spends tokens again.
    private var regenerateButton: some View {
        Button {
            Task { await model.generateRetrospectiveTopics() }
        } label: {
            HStack(spacing: 5) {
                if model.isGeneratingRetro {
                    ProgressView().controlSize(.small)
                    Text("Cooking…")
                } else {
                    Image(systemName: "arrow.clockwise")
                    Text("Regenerate")
                }
            }
            .font(.caption)
        }
        .buttonStyle(.borderless)
        .disabled(model.isGeneratingRetro)
        .help("Re-run the local claude CLI — spends tokens again.")
    }

    private var generatePrompt: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Get coaching on how to use your tokens better — model choice, context hygiene, automation balance, pacing.")
                .font(.callout).foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
            Button {
                Task { await model.generateRetrospectiveTopics() }
            } label: {
                HStack(spacing: 6) {
                    if model.isGeneratingRetro {
                        ProgressView().controlSize(.small)
                        Text("Cooking…")
                    } else {
                        Image(systemName: "sparkles")
                        Text("Coach me")
                    }
                }
            }
            .buttonStyle(.borderedProminent)
            .disabled(model.isGeneratingRetro)
            // 먹방 paradox, stated honestly: this bite spends tokens (ADR-0020).
            Text("Analyzes yesterday's usage with your local claude CLI — this bite spends tokens.")
                .font(.caption2).foregroundStyle(.tertiary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private var degradeNote: some View {
        Label {
            Text("claude CLI not found — showing activity only. Install Claude Code for topic insights.")
                .fixedSize(horizontal: false, vertical: true)
        } icon: {
            Image(systemName: "wand.and.stars.inverse")
        }
        .font(.caption).foregroundStyle(.secondary)
    }

    private var emptyState: some View {
        GlassTile(scheme: scheme) {
            VStack(alignment: .leading, spacing: 6) {
                Text("NO PLATE YET").dsEyebrow()
                Text("No tokens were eaten yesterday. Come back after a session.")
                    .font(.callout).foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(DS.section)
        }
    }

    // MARK: Small building blocks

    private func section<Content: View>(_ title: String, @ViewBuilder _ content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: DS.intra) {
            Text(title).dsEyebrow()
            content()
        }
    }

    private func row(_ name: String, _ value: String, fraction: Double) -> some View {
        HStack(spacing: 8) {
            Text(name).font(.callout).lineLimit(1)
            Spacer(minLength: 8)
            GeometryReader { geo in
                Capsule().fill(mood.accent.opacity(0.25))
                    .frame(width: max(2, geo.size.width * fraction))
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .frame(width: 60, height: 5)
            Text(value).font(DS.captionFont.monospacedDigit()).foregroundStyle(.secondary)
                .frame(width: 52, alignment: .trailing)
        }
    }

    private func sourceNote(_ topics: RetroTopics) -> String {
        switch topics.source {
        case .claudeCLI: return "Analyzed locally by your claude CLI."
        case .keyword:   return "From local keywords (no model)."
        }
    }

    // MARK: Formatting helpers (token/peak/date formatting is shared in Kit — RetrospectiveSummary)

    private func frac(_ part: Int, _ whole: Int) -> Double {
        whole > 0 ? min(1, Double(part) / Double(whole)) : 0
    }
}
